'use strict';

const AUTH_CODES = {
  UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  RATE_LIMITED: 'AUTH_RATE_LIMITED'
};

const AUTH_POLICY = {
  MAX_LOGIN_ATTEMPTS: 5,
  ACCOUNT_LOCK_MINUTES: 30
};

module.exports = {
  AUTH_CODES,
  AUTH_POLICY
};
